name: stackfood_multivendor
description: A new Flutter application.
publish_to: 'none' #
version: 1.0.5+7

environment:
  sdk: '>=3.2.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  get: ^4.6.6
  video_player: ^2.4.10
  firebase_auth:
  otp_text_field: ^1.1.3
  shared_preferences: ^2.0.15
  connectivity_plus: ^5.0.2
  firebase_core: ^2.4.1
  firebase_messaging: ^14.2.1
  flutter_local_notifications: ^19.2.1
  path_provider: ^2.0.8
  url_strategy: ^0.2.0
  pin_code_fields: ^8.0.1
  geolocator: ^10.1.0
  google_maps_flutter: ^2.6.0
  google_maps_flutter_web: ^0.5.6+2
  carousel_slider: ^5.0.0
  shimmer_animation: ^2.1.0+1
  image_picker: ^1.0.7
  universal_html: ^2.0.8
  flutter_inappwebview: ^6.0.0
  url_launcher: ^6.0.17
  http: ^1.2.1
  pointer_interceptor: ^0.10.1+2
  phone_numbers_parser: ^8.1.3
  country_code_picker: ^3.0.0
  cached_network_image: ^3.3.0
  supabase_flutter: ^2.8.1
  google_sign_in: ^6.2.2
  google_sign_in_web: ^0.12.4+3
  flutter_facebook_auth: ^7.1.1
  photo_view: ^0.14.0
  dotted_border: ^2.0.0+2
  share_plus: ^7.2.1
  custom_map_markers: ^0.0.2+1
  flutter_image_compress: ^2.4.0
  card_swiper: ^3.0.1
  expandable_bottom_sheet: ^1.1.1+1
  sign_in_with_apple: ^5.0.0
  flutter_web_auth: ^0.6.0
  flutter_html:
    git:
      url: https://github.com/cgs/flutter_html
      ref: alpha-6-flutter-322
  flutter_widget_from_html: ^0.14.11
  intl: ^0.19.0
  flutter_slidable: ^4.0.0
  just_the_tooltip: ^0.0.12
  animated_flip_counter: ^0.2.0
  meta_seo: ^3.0.5
  fluttertoast: ^8.2.4
  marquee: ^2.2.3
  syncfusion_flutter_datepicker: ^24.1.45
  firebase_crashlytics: ^3.4.3
  file_picker: ^6.2.0
  path: ^1.8.2
  http_parser: ^4.0.2
  flutter_svg: ^2.0.10+1
  flutter_secure_storage: ^9.2.4
  webview_flutter: ^4.8.0
#  flutter_polyline_points: ^2.0.0
  custom_info_window: ^1.0.1
  win32: ^5.5.4


dependency_overrides:
  fading_edge_scrollview: ^4.1.1
  archive: ^3.4.11


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1
  change_app_package_name: ^1.4.0

flutter:
  uses-material-design: true

  assets:
    - assets/image/
    - assets/language/
    - assets/map/
    - assets/image/dark.png
    - assets/videos/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/font/Roboto-Regular.ttf
          weight: 400
        - asset: assets/font/Roboto-Medium.ttf
          weight: 500
        - asset: assets/font/Roboto-Bold.ttf
          weight: 700
        - asset: assets/font/Roboto-Black.ttf
          weight: 900